### ISSUE TITLE
Documentation update/Creation

### ISSUE THREAD

**Issue by GeneralG** [GeniiDevCore/DevWebApps_Training#13]
Documentation needs to be updated to reflect correct logic being down in the application.
This refers to the logic where weighting is calculated against the answer or against the question. 
Refrences the following issue and the documentation may need to be updated once the following issue is complete. 

https://github.com/GeniiDevCore/DevWebApps_IA_core/issues/2120

Add documentation to the reporting that indicates how the weighting is calculated off the answer and how that will effect the reporting.

**Comment by LynnGenii** [comment]
Done
https://github.com/GeniiDevCore/DevWebApps_Training/issues/18
https://github.com/GeniiDevCore/DevWebApps_Training/issues/19
https://github.com/GeniiDevCore/DevWebApps_Training/issues/20
