### ISSUE TITLE
Data connector - Data Model and Data Dictionary. 

### ISSUE THREAD

**Issue by GeneralG** [GeniiDevCore/DevWebApps_Training#14]
Create 2 different documents that will be used to represent the Data Model and the Data Dictionary. 

Data Model 
- Diagram representing the core views available to the data connector. 
- Specifications on what views will be used as primary and secondary views. 
- - Need to specify secondary views are not guaranteed and may be removed if it causes to much overhead on the servers. 

Data Dictionary:
- Word document that will be used to explain and elaborate on the columns in the tables to the user that has access to the DB connector. 
- Each column needs to have a definition. 
- These are only the columns inn the core views. Secondary views will not get a data model.

**Comment by GeneralG** [comment]
Initial document please comment: 
https://github.com/GeniiDevCore/DevWebApps_Training/raw/master/Training%20Docs/GeniiDB%20-%20DataModel.docx

We will need to create new views: 
- v_Persons
- v_Audits

**Comment by RushBaderoen** [comment]
Doc looks good so far. Definitely needs info about Audits & Persons

I don't see any mention of Feedbacks though. Not sure if that was intentional, but we will probably need it at some point.

**Comment by GeneralG** [comment]
Should we put the, these are the views for viewing the changes of an assessment over time. 
- v_QAauditsBicaptures
- v_QAauditsQaCaptures

**Comment by GeneralG** [comment]
Please look at the following article. 

https://prd-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/atoms/files/Top%20Ten%20Metadata%20Mistakes_20201218_508compliant.pdf
https://www.usgs.gov/products/data-and-tools/data-management/data-dictionaries
https://www.sciencedirect.com/topics/computer-science/data-dictionary

We will need to update the data dictionary, it seems to be alot bigger than originally expected. 

Concerning what other values we need to put in will be a bit complicated as it is based on the user input.

**Comment by GeneralG** [comment]
https://github.com/GeniiDevCore/DevWebApps_IA_core/issues/2125

**Comment by GeneralG** [comment]
Make sure to specify which columns have numbers masked.

**Comment by GeneralG** [comment]
This took me way longer than 0.25 days.
