### ISSUE TITLE
Request - Create a link for Data Model and Data Dictionary on the app

### ISSUE THREAD

**Issue by LynnGenii** [GeniiDevCore/DevWebApps_Training#16]
Please add an info button in position suggested in yellow (2nd screen shot) and add to Knowledge base

link to https://github.com/GeniiDevCore/DevWebApps_Training/raw/master/Training%20Docs/GeniiDB%20-%20DataModel.docx

Name: Data Model and Data Dictionary
Description: Details about our data models 
Hover Message: Data Model and Data Dictionary

![image](https://user-images.githubusercontent.com/45848960/116376157-45dd3480-a810-11eb-9287-eafe7880d56a.png)

![image](https://user-images.githubusercontent.com/45848960/116375875-fc8ce500-a80f-11eb-8251-cf79bd25f242.png)

**Comment by GeneralG** [comment]
the PDF version will be added only once the doc is completed.

**Comment by GeneralG** [comment]
https://github.com/GeniiDevCore/DevWebApps_Training/issues/14
