### ISSUE TITLE
Create Weighted AQA & QA Documentation

### ISSUE THREAD

**Issue by LynnGenii** [GeniiDevCore/DevWebApps_Training#18]
Create documentation detailing the logic used for these products

**Comment by LynnGenii** [comment]
pre-lim documentation - please review and comment

[Weighted AQA and QA.docx](https://github.com/GeniiDevCore/DevWebApps_Training/files/6520661/Weighted.AQA.and.QA.docx)

**Comment by GeneralG** [comment]
[Weighted.AQA.and.QA.docx](https://github.com/GeniiDevCore/DevWebApps_Training/files/6521480/Weighted.AQA.and.QA.docx)

**Comment by GeneralG** [comment]
lef comments

**Comment by LynnGenii** [comment]
@GeneralG we only have documentation for updating the dates not anything else.
Sorry guys that was a old version i posted. this is the updated one.

[Weighted AQA and QA.docx](https://github.com/GeniiDevCore/DevWebApps_Training/files/6522239/Weighted.AQA.and.QA.docx)

**Comment by azoladyantyi** [comment]
I went through the doc and I approve it

**Comment by LynnGenii** [comment]
[Weighted AQA and QA.docx](https://github.com/GeniiDevCore/DevWebApps_Training/files/6538668/Weighted.AQA.and.QA.docx)

**Comment by valerie-geniianalytics** [comment]
Approved, looks good,  icons definition page only one remaining

**Comment by LynnGenii** [comment]
Updated icon page.
if anyone can get me a pic of the export one we use on the app (not 3schools as i can't get it off there.) it would be great.

[Weighted AQA and QA.docx](https://github.com/GeniiDevCore/DevWebApps_Training/files/6546373/Weighted.AQA.and.QA.docx)

**Comment by LynnGenii** [comment]
[Weighted AQA and QA.docx](https://github.com/GeniiDevCore/DevWebApps_Training/files/6552215/Weighted.AQA.and.QA.docx)

**Comment by valerie-geniianalytics** [comment]
approved

**Comment by LynnGenii** [comment]
Hi all, i've created a scaled down version to be added to the knowledge base.
the original will be added to the repo, but i prefer this one to go to clients for now.

please check and advise

[Weighted AQA & QA Logic.docx](https://github.com/GeniiDevCore/DevWebApps_Training/files/6575160/Weighted.AQA.QA.Logic.docx)

**Comment by GeneralG** [comment]
![image](https://user-images.githubusercontent.com/321024/120305942-a1985300-c2d1-11eb-92d4-81f55815041a.png)

**Comment by LynnGenii** [comment]
![image](https://user-images.githubusercontent.com/321024/120305942-a1985300-c2d1-11eb-92d4-81f55815041a.png)

new paragraph

**Comment by GeneralG** [comment]
![image](https://user-images.githubusercontent.com/321024/120307230-07390f00-c2d3-11eb-879b-bb671bac01cd.png)

**Comment by GeneralG** [comment]
![Uploading image.png…]()

**Comment by GeneralG** [comment]
![image](https://user-images.githubusercontent.com/321024/120307502-5b43f380-c2d3-11eb-8134-39e867ebca71.png)

**Comment by GeneralG** [comment]
![image](https://user-images.githubusercontent.com/321024/120308859-d5c14300-c2d4-11eb-8751-ecbdb1aa8398.png)

This is the calculations that are applied as you traverse up the tree to a section, when looking at a section or higher we use the following calculations. 

    sum of applied weight / sum applicable weight * 100

**Comment by LynnGenii** [comment]
updated file with Tyler's suggestion , quite a change please check calculation section
[Weighted AQA & QA Logic.docx](https://github.com/GeniiDevCore/DevWebApps_Training/files/6575738/Weighted.AQA.QA.Logic.docx)

**Comment by LynnGenii** [comment]
Cleaned up a bit
[Weighted AQA & QA Logic.docx](https://github.com/GeniiDevCore/DevWebApps_Training/files/6576715/Weighted.AQA.QA.Logic.docx)

**Comment by valerie-geniianalytics** [comment]
- [ ] Numbers error
![image](https://user-images.githubusercontent.com/48471800/120762954-0ee8f580-c517-11eb-8687-7b550e741141.png)

**Comment by valerie-geniianalytics** [comment]
Apart from those two points, everything else looks fine, approved

**Comment by RushBaderoen** [comment]
Looks fine except I was a bit confused by the example on p.9. My assumption was that the "Call 1" being mentioned at the bottom is the one in the example, but apparently there is a different "Call 1" on p.8
![image](https://user-images.githubusercontent.com/48755401/120793214-ea047a80-c536-11eb-9b74-6117110b5069.png)

**Comment by LynnGenii** [comment]
> Looks fine except I was a bit confused by the example on p.9.
> 
> My assumption was that the "Call 1" being mentioned at the bottom of the page is the one in the example above it, but it seems like you are actually referring to the other "Call 1" on p.8
> 
> Might help to rename some of the calls to avoid conflict
> 
> Page 8
> ![image](https://user-images.githubusercontent.com/48755401/120793364-17e9bf00-c537-11eb-8248-815434356961.png)
> 
> Page 9
> ![image](https://user-images.githubusercontent.com/48755401/120793214-ea047a80-c536-11eb-9b74-6117110b5069.png)

you are correct, i'm referring to call 1 on page 8. the tables on page 9 came after.
should i take that part out?
or just add that _with reference to the table on Page8_

**Comment by LynnGenii** [comment]
Updated with captions as per Rushdi's recommendation

[Weighted AQA and QA.docx](https://github.com/GeniiDevCore/DevWebApps_Training/files/6598603/Weighted.AQA.and.QA.docx)
[Weighted AQA & QA Logic.docx](https://github.com/GeniiDevCore/DevWebApps_Training/files/6598604/Weighted.AQA.QA.Logic.docx)

**Comment by RushBaderoen** [comment]
Looking better. Approved 👍

**Comment by valerie-geniianalytics** [comment]
approved
