### ISSUE TITLE
Updated Personnel Manager Documentation

### ISSUE THREAD

**Issue by LynnGenii** [GeniiDevCore/DevWebApps_Training#21]
Please review updated Personnel Manager Documentation.
- csv allocation
[Personel Manager Training Manual V2.docx](https://github.com/GeniiDevCore/DevWebApps_Training/files/6752365/Personel.Manager.Training.Manual.V2.docx)

Sent to Nics, Siska & Lizelle for review as well

**Comment by azoladyantyi** [comment]
on page can you please change the format and  use bullet points so that the list looks nicely
![image](https://user-images.githubusercontent.com/23166122/124259317-ac434380-db2e-11eb-8d67-23eff346a01b.png)

**Comment by LynnGenii** [comment]
[Personel Manager Training Manual V2.docx](https://github.com/GeniiDevCore/DevWebApps_Training/files/6754003/Personel.Manager.Training.Manual.V2.docx)



> on page 31 can you please change the format and use bullet points so that the list looks nicely
> ![image](https://user-images.githubusercontent.com/23166122/124259317-ac434380-db2e-11eb-8d67-23eff346a01b.png)

![image](https://user-images.githubusercontent.com/45848960/124261783-7f446000-db31-11eb-9646-fae4e9a53564.png)

**Comment by azoladyantyi** [comment]
approved

**Comment by GeneralG** [comment]
approved.

**Comment by valerie-geniianalytics** [comment]
approved

**Comment by terafirma92** [comment]
![image](https://user-images.githubusercontent.com/86767376/124621189-5ba74f80-de7a-11eb-9ffd-9640dd6c35bf.png)

On page 7, `indiviual` -> `individual`

there is also one on the next page

![image](https://user-images.githubusercontent.com/86767376/124619084-9f995500-de78-11eb-937e-ca244a3ed31f.png)

I assume `delete`? on Page 8

![image](https://user-images.githubusercontent.com/86767376/124619314-d7080180-de78-11eb-8432-d6ef9130f698.png)

The above is on page 9, `colomns` -> `columns`

![image](https://user-images.githubusercontent.com/86767376/124619495-fef76500-de78-11eb-8c0c-e8b706d16cfd.png)

On page 11, `compultory` -> `compulsory`

![image](https://user-images.githubusercontent.com/86767376/124619739-3108c700-de79-11eb-9642-df7b15c8a38a.png)

On page 16, and another on page 17 in the first sentance

![image](https://user-images.githubusercontent.com/86767376/124620255-98bf1200-de79-11eb-98d8-ae1a4fd99202.png)

On page 21, `camapaigns` -> `campaigns`, `assocaited` -> `associated`

![image](https://user-images.githubusercontent.com/86767376/124620501-ca37dd80-de79-11eb-96e2-ef33c1fe7aae.png)

On page 22, `verson` -> `version`

![image](https://user-images.githubusercontent.com/86767376/124620719-fc493f80-de79-11eb-9ca1-5746d2623c9f.png)

On page 31, `coloum` -> `column`



I'm sorry
