### ISSUE TITLE
Create Alert Notification Documentation

### ISSUE THREAD

**Issue by LynnGenii** [GeniiDevCore/DevWebApps_Training#29]
[Alert Notification Process.docx](https://github.com/GeniiDevCore/DevWebApps_Training/files/7526783/Alert.Notification.Process.docx)

**Comment by GeneralG** [comment]
Please update this part to have links to the documents on github. 

![image](https://user-images.githubusercontent.com/321024/141468063-dbe4217b-9574-4dea-b47a-7d304950ff24.png)

**Comment by LynnGenii** [comment]
> Please update this part to have links to the documents on github.
> 
> ![image](https://user-images.githubusercontent.com/321024/141468063-dbe4217b-9574-4dea-b47a-7d304950ff24.png)

don
[Alert Notification Process.docx](https://github.com/GeniiDevCore/DevWebApps_Training/files/7527626/Alert.Notification.Process.docx)
e

**Comment by GeneralG** [comment]
Your links are to the C:\ and not to the web address.

**Comment by LynnGenii** [comment]
> Your links are to the C:\ and not to the web address.

Done

[Uploading Alert Notification Process.docx…]()
